# Generated by Django 2.2.4 on 2022-10-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to='loginApp.loges')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='mesg_commit_id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_commit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commit', to='loginApp.loges'),
        ),
        migrations.DeleteModel(
            name='messages',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='comments',
            name='msg_commit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='firstapp.msgs'),
            preserve_default=False,
        ),
    ]
