# Generated by Django 2.2.4 on 2022-10-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20221004_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='coment',
        ),
    ]
