# Generated by Django 2.2.4 on 2022-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20221004_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='msg_commit_id',
            new_name='commit_in_message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_commit_id',
            new_name='user_who_commit',
        ),
        migrations.RenameField(
            model_name='msgs',
            old_name='user_msg_id',
            new_name='user_who_msg',
        ),
        migrations.AlterField(
            model_name='comments',
            name='coment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
