# Generated by Django 2.2.4 on 2022-10-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20221005_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msgs',
            old_name='msg',
            new_name='message',
        ),
    ]
