# Generated by Django 2.2.4 on 2022-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20221005_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commit_on_message',
            new_name='msg_commit_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_who_commit',
            new_name='user_commit_id',
        ),
        migrations.RenameField(
            model_name='msgs',
            old_name='message',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='msgs',
            old_name='user_who_msg',
            new_name='user_msg_id',
        ),
    ]
