# Generated by Django 2.2.4 on 2022-10-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20221005_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='msg_commit_id',
            new_name='commit_on_message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_commit_id',
            new_name='user_who_commit',
        ),
        migrations.RenameField(
            model_name='msgs',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='msgs',
            old_name='user_msg_id',
            new_name='user_who_msg',
        ),
    ]
