# Generated by Django 4.1.1 on 2022-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_loges_brithday'),
    ]

    operations = [
        migrations.AddField(
            model_name='loges',
            name='brithday',
            field=models.DateField(null=True),
        ),
    ]
