# Generated by Django 4.1.1 on 2022-10-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_users_realseddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='RealsedDate',
        ),
    ]
