# Generated by Django 4.1.1 on 2022-10-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_show_userkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='userKey',
        ),
    ]
