# Generated by Django 2.2.4 on 2022-10-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favApp', '0002_auto_20221004_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_book',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='fav_book',
            new_name='users_who_like',
        ),
    ]
