# Generated by Django 2.2.4 on 2022-10-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favApp', '0004_auto_20221006_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbortary',
            old_name='made_by',
            new_name='planded_by',
        ),
    ]
