# Generated by Django 2.2.4 on 2022-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favApp', '0005_auto_20221006_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbortary',
            name='location',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='arbortary',
            name='reason',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arbortary',
            name='species',
            field=models.CharField(max_length=5),
        ),
    ]
