# Generated by Django 2.2.4 on 2022-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default='This is a show description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(default='This is a show title'),
        ),
    ]
